[package]
name = "valkey-bloom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis-module = "2.0.7"
bloomfilter = "1.0.13"
lazy_static = "1.4.0"
libc = "0.2"

[build-dependencies]
cc = "1.0.73"
bindgen = "0.60.1"

[lib]
crate-type = ["cdylib"]
name = "valkey_bloom"
