name: ci

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  REPO_URL: https://github.com/valkey-io/valkey.git

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['unstable']
    steps:
    - uses: actions/checkout@v4
    - name: Update tests dir path
      run: echo "TEST_DIR=$(pwd)/tests" >> $GITHUB_ENV
    - name: Set verison for tests
      run: echo "VERSION=${{ matrix.version }}" >> $GITHUB_ENV
    - name: Run cargo and clippy format check
      run: |
        cargo fmt --check
        cargo clippy --profile release --all-targets -- -D clippy::all
    - name: Build
      run: cargo build --all --all-targets  --release
    # Waiting for a new feature in the valkey-module-rs to be released which will allow unit testing of Valkey Rust modules
    # - name: Run tests
    #   run: cargo test --verbose
    - name: Make valkey-server binary
      run: |
        mkdir -p "tests/.build/binaries/${{ matrix.version }}"
        cd tests/.build
        rm -rf valkey
        git clone "${{ env.REPO_URL }}"
        cd valkey
        git checkout ${{ matrix.version }}
        make
        cp src/valkey-server ../binaries/${{ matrix.version }}/
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update module path
      run: echo "MODULE_PATH=$(realpath target/release/libvalkey_bloom.so)" >> $GITHUB_ENV
    - name: Run integration tests 
      run: python -m pytest --cache-clear -v "${{ env.TEST_DIR }}"
    - name: Show log files if failure occured
      if: ${{ failure() }}
      run: find . -name "*logfile*" | xargs cat tail 500
